// API ACTIONS
export const API_GET_POSTS = '[POSTS]_API_GET_POSTS'
export const API_GET_FILTERED_POSTS_BY_USER_ID = '[POSTS] API_GET_FILTERED_POSTS_BY_USER_ID'

// STATE ACTIONS
export const DOWNLOAD_POSTS = '[POSTS]_DOWNLOAD_POSTS'
